name: "Setup Node Environment"
description: "Set up the build environment for a Node project"

inputs:
  runtime_version:
    description: "The default Node runtime version to run builds on"
    required: false
    default: "24.x"

runs:
  using: "composite"
  steps:
    - name: "checkout"
      uses: "actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803" # v6.1.0
    - name: "node.js ${{ inputs.runtime_version }}"
      uses: "actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38" # v6.5.0
      with:
        node-version: "${{ inputs.runtime_version }}"
        cache: "yarn"
    - name: "yarn dependencies"
      shell: "bash"
      run: "yarn install --immutable"

