name: "Setup Node Environment"
description: "Set up the build environment for a Node project"

inputs:
  runtime_version:
    description: "The default Node runtime version to run builds on"
    required: false
    default: "20.x"
  
runs:
  using: "composite"
  steps:
    - name: "checkout"
      uses: "actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955" # v4.3.0
    - name: "node.js ${{ inputs.runtime_version }}"
      uses: "actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020" # v4.4.0
      with:
        node-version: "${{ inputs.runtime_version }}"
        cache: "yarn"
    - name: "yarn dependencies"
      shell: "bash"
      run: "yarn install --immutable"

