name: "Setup Java Environment"
description: "Set up the build environment for a Java project"

inputs:
  runtime_version:
    description: "The default Java runtime version to run builds on"
    required: true
  publishing_branch_regex:
    description: "The regular expression to determine if a certain branch build should be published"
    required: true
  gradle_warning_mode:
    description: "Warning mode to set on Gradle executions"
    required: false
    default: "fail"
outputs:
  publishing_branch:
    description: "The branch name, if it is a publishing branch, or an empty string if not"
    value: "${{ steps.branch-name.outputs.match }}"

runs:
  using: "composite"
  steps:
    - name: "checkout"
      uses: "actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd" # v6.0.2
      with:
        fetch-depth: 0
        submodules: true
    - name: "jdk ${{ inputs.runtime_version }}"
      uses: "actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654" # v5.2.0
      with:
        distribution: "zulu"
        java-version: "${{ inputs.runtime_version }}"
    # Checks branch name to see if we're going to potentially publish this
    - name: "publishing branch"
      uses: "KyoriPowered/action-regex-match@5684ded1f3e016437483d3d74cfa93fcdf5e313b" # v5.0.0
      id: "branch-name"
      with:
        text: "${{ github.ref }}"
        regex: "^refs/heads/(?:${{ inputs.publishing_branch_regex }})$" # master or something like 0.8.x or 2.x
    - name: "gradle / setup properties"
      env:
        WARNING_MODE: "${{ inputs.gradle_warning_mode }}"
      shell: bash
      run: |
        exec "$GITHUB_ACTION_PATH/setup-gradle-properties.sh"
    - name: "gradle / setup environment"
      uses: "gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2" # v5.0.0
      with:
        dependency-graph: "generate-and-upload"
        cache-read-only: "${{ (steps.branch-name.outputs.match == '' || github.event_name == 'pull_request') && !startsWith(github.ref, 'refs/heads/gh-readonly-queue/') }}"
