name: "test"

on:
  workflow_call:

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "setup"
        uses: "KyoriPowered/.github/.github/actions/setup-node-env@trunk"
      - name: "test"
        run: "yarn test"
      - name: "check format"
        run: "yarn format-check"
      - name: "lint"
        run: "yarn lint"
