
name: "rebuild docs"

on:
  workflow_call:
    secrets:
      DEPLOYMENT_APP_ID:
        description: "A GitHub app ID used to request a token"
        required: true
      DEPLOYMENT_APP_SECRET:
        description: "A GitHub app key used to request a token"
        required: true

concurrency:
  group: "rebuild-docs"
  cancel-in-progress: true

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "authenticate"
        id: "authenticate"
        uses: "tibdex/github-app-token@021a240" # renovate: tag=v1
        with:
          app_id: "${{ secrets.DEPLOYMENT_APP_ID }}"
          private_key: "${{ secrets.DEPLOYMENT_APP_SECRET }}"
      - name: "Dispatch event"
        uses: "actions/github-script@v6"
        with:
          github-token: "${{ steps.authenticate.outputs.token }}"
          script: |
            github.rest.repos.createDispatchEvent({
              owner: 'KyoriPowered',
              repo: 'adventure-docs',
              type: 'rebuild-docs'
            })
