
name: "rebuild docs"

on:
  workflow_call:
    secrets:
      DEPLOYMENT_APP_ID:
        description: "A GitHub app ID used to request a token"
        required: true
      DOCS_INSTALLATION_ID:
        description: "The ID of the appropriate installation for adventure-docs"
        required: true
      DEPLOYMENT_APP_SECRET:
        description: "A GitHub app key used to request a token"
        required: true

concurrency:
  group: "rebuild-docs"
  cancel-in-progress: true

permissions:
  contents: "read"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "authenticate"
        id: "authenticate"
        uses: "tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92" # v1
        with:
          app_id: "${{ secrets.DEPLOYMENT_APP_ID }}"
          installation_id: "${{ secrets.DOCS_INSTALLATION_ID }}"
          private_key: "${{ secrets.DEPLOYMENT_APP_SECRET }}"
      - name: "Dispatch event"
        uses: "actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410" # v6
        with:
          github-token: "${{ steps.authenticate.outputs.token }}"
          script: |
            github.rest.repos.createDispatchEvent({
              owner: 'KyoriPowered',
              repo: 'adventure-docs',
              event_type: 'rebuild-docs'
            })
