name: Run CI

on:
  workflow_call:
    inputs:
      runtime_version:
        description: 'The default Java runtime version to run builds on'
        required: false
        type: number
        default: 11
      publishing_branch_regex:
        description: 'The regular expression to determine if a certain branch build should be published'
        required: false
        type: string
        default: '(?:(?:(?:main\/)?(\d+(?:\.\d+)*(?:\.x)?)))|master|main|trunk'
      extra_gradle_params:
        description: 'Extra arguments to pass to all Gradle invocations'
        required: false
        type: string
        default: ''
      extra_gradle_publish_params:
        description: 'Extra arguments to pass to the Gradle invocation that publishes this project'
        required: false
        type: string
        default: ''
      gradle_warning_mode:
        description: 'Warning mode to set on Gradle executions'
        required: false
        type: string
        default: 'fail'
    secrets:
      SONATYPE_USERNAME:
        description: 'Kyori OSSRH Username'
        required: false
      SONATYPE_PASSWORD:
        description: 'Kyori OSSRH Password'
        required: false
      STELLARDRIFT_USERNAME:
        description: 'Kyori Stellardrift Repository Username'
        required: false
      STELLARDRIFT_PASSWORD:
        description: 'Kyori Stellardrift Repository Password'
        required: false
      KYORI_GPG_KEY:
        description: 'Kyori GPG signing key'
        required: false
      KYORI_GPG_PASSWORD:
        description: 'Kyori GPG signing password'
        required: false

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

permissions:
  actions: "write"
  contents: "read"

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "checkout repository"
        uses: "actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9" # v3
        with:
          fetch-depth: 0
          submodules: true
      - name: "setup jdk ${{ inputs.runtime_version }}"
        uses: "actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2" # v3
        with:
          distribution: "temurin"
          java-version: "${{ inputs.runtime_version }}"
      - name: "validate gradle wrapper"
        uses: "gradle/wrapper-validation-action@55e685c48d84285a5b0418cd094606e199cca3b6" # v1
      # Checks branch name to see if we're going to potentially publish this
      - name: "check branch for publish"
        uses: "KyoriPowered/action-regex-match@6d2048eb7022801ce27e9889d02bcef10ac616fe" # v3
        id: "branch-name"
        with:
          text: "${{ github.ref }}"
          regex: "^refs/heads/(?:${{ inputs.publishing_branch_regex }})$" # master or something like 0.8.x or 2.x
      - name: "setup gradle properties"
        env:
          WARNING_MODE: "${{ inputs.gradle_warning_mode }}"
        shell: bash
        run: |
          mkdir -p $HOME/.gradle/
          echo "org.gradle.warning.mode=$WARNING_MODE" >> $HOME/.gradle/gradle.properties
      - name: "run gradle build"
        uses: "gradle/gradle-build-action@40b6781dcdec2762ad36556682ac74e31030cfe2" # v2
        with:
          cache-read-only: "${{ steps.branch-name.outputs.match == '' || github.event_name == 'pull_request' }}"
          arguments: " ${{ inputs.extra_gradle_params }} build"
      - name: "Archive test results"
        if: "${{ always() }}"
        uses: "actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce" # v3
        with:
          name: "${{ runner.os }}-test-results"
          path: |
            build/reports/
            */build/reports/
      - name: Determine status
        if: "${{ runner.os == 'Linux' }}"
        run: |
          if [ "$(./gradlew properties | awk '/^version:/ { print $2; }' | grep '\-SNAPSHOT')" ]; then
            echo "STATUS=snapshot" >> $GITHUB_ENV
          else
            echo "STATUS=release" >> $GITHUB_ENV
          fi
      - name: "publish"
        if: "${{ runner.os == 'Linux' && env.STATUS != 'release' && github.event_name == 'push' && steps.branch-name.outputs.match != '' }}"
        run: "./gradlew ${{ inputs.extra_gradle_params }} publish ${{ inputs.extra_gradle_publish_params }}"
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: "${{ secrets.SONATYPE_USERNAME }}"
          ORG_GRADLE_PROJECT_sonatypePassword: "${{ secrets.SONATYPE_PASSWORD }}"
          ORG_GRADLE_PROJECT_stellardriftUsername: "${{ secrets.STELLARDRIFT_USERNAME }}"
          ORG_GRADLE_PROJECT_stellardriftPassword: "${{ secrets.STELLARDRIFT_PASSWORD }}"
          ORG_GRADLE_PROJECT_kyoriSigningKey: "${{ secrets.KYORI_GPG_KEY }}"
          ORG_GRADLE_PROJECT_kyoriSigningPassword: "${{ secrets.KYORI_GPG_PASSWORD }}"
