name: Run CI

on:
  workflow_call:
    inputs:
      runtime_version:
        description: 'The default Java runtime version to run builds on'
        required: false
        type: number
        default: 17
      publishing_branch_regex:
        description: 'The regular expression to determine if a certain branch build should be published'
        required: false
        type: string
        default: '(?:(?:(?:main\/)?(\d+(?:\.\d+)*(?:\.x)?)))|master|main|trunk'
      extra_gradle_params:
        description: 'Extra arguments to pass to all Gradle invocations'
        required: false
        type: string
        default: ''
      extra_gradle_publish_params:
        description: 'Extra arguments to pass to the Gradle invocation that publishes this project'
        required: false
        type: string
        default: ''
      gradle_release_publish_tasks:
        description: 'Extra tasks to pass to the Gradle invocation that publishes releases of this project'
        required: false
        type: string
        default: 'publishToSonatype closeAndReleaseSonatypeStagingRepository'
      gradle_warning_mode:
        description: 'Warning mode to set on Gradle executions'
        required: false
        type: string
        default: 'fail'
      publish_releases:
        description: 'Whether to publish releases of this project. The gradle_release_publish_params input must be provided when publishing to anything but Sonatype Central'
        required: false
        type: boolean
        default: false
      publish_release_javadoc:
        description: 'Whether to publish Javadocs on release'
        required: false
        type: boolean
        default: false
      javadoc_deploy_prefix:
        description: 'Extra subdirectory to publish javadoc under'
        required: false
        type: string
        default: ''
    secrets:
      SONATYPE_USERNAME:
        description: 'Kyori OSSRH Username'
        required: false
      SONATYPE_PASSWORD:
        description: 'Kyori OSSRH Password'
        required: false
      STELLARDRIFT_USERNAME:
        description: 'Kyori Stellardrift Repository Username'
        required: false
      STELLARDRIFT_PASSWORD:
        description: 'Kyori Stellardrift Repository Password'
        required: false
      PAPERMC_USERNAME:
        description: 'Kyori PaperMC Repository Username'
        required: false
      PAPERMC_PASSWORD:
        description: 'Kyori PaperMC Repository Password'
        required: false
      KYORI_REPO_USERNAME:
        description: 'Kyori Repository Username'
        required: false
      KYORI_REPO_PASSWORD:
        description: 'Kyori Repository Password'
        required: false
      KYORI_GPG_KEY:
        description: 'Kyori GPG signing key'
        required: false
      KYORI_GPG_PASSWORD:
        description: 'Kyori GPG signing password'
        required: false
      DEPLOYMENT_APP_ID:
        description: 'App id for JD publisher'
        required: false
      DEPLOYMENT_APP_SECRET:
        description: 'App key for JD publisher'
        required: false
      KYORI_PLUGIN_PORTAL_API_KEY:
        description: 'Kyori Gradle Plugin Portal API key'
        required: false
      KYORI_PLUGIN_PORTAL_API_SECRET:
        description: 'Kyori Gradle Plugin Portal API secret'
        required: false

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

permissions:
  actions: "write"
  contents: "read"
  id-token: "write"

jobs:
  build:
    # Only run on PRs if the source branch is on someone else's repo
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "setup environment"
        id: "setup"
        uses: "KyoriPowered/.github/.github/actions/setup-java-env@trunk"
        with:
          runtime_version: "${{ inputs.runtime_version }}"
          publishing_branch_regex: "${{ inputs.publishing_branch_regex }}"
          gradle_warning_mode: "${{ inputs.gradle_warning_mode }}"
      - name: "run gradle build"
        run: "./gradlew ${{ inputs.extra_gradle_params }} build"
      - name: "archive test results"
        if: "${{ always() }}"
        uses: "actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02" # v4.6.2
        with:
          name: "${{ runner.os }}-test-results"
          path: |
            build/reports/
            */build/reports/
      - name: "determine status & prepare for publish"
        if: "${{ runner.os == 'Linux' }}"
        run: |
          # Disable dependency graph generation after first build, plus for this step itself
          echo "GITHUB_DEPENDENCY_GRAPH_ENABLED=false" >> $GITHUB_ENV
          export GITHUB_DEPENDENCY_GRAPH_ENABLED=false

          if [ "$(./gradlew properties | awk '/^version:/ { print $2; }' | grep '\-SNAPSHOT')" ]; then
            echo "STATUS=snapshot" >> $GITHUB_ENV
          else
            echo "STATUS=release" >> $GITHUB_ENV
          fi
      - name: "publish snapshot"
        if: "${{ runner.os == 'Linux' && env.STATUS != 'release' && github.event_name == 'push' && steps.setup.outputs.publishing_branch != '' }}"
        run: "./gradlew ${{ inputs.extra_gradle_params }} publish ${{ inputs.extra_gradle_publish_params }}"
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: "${{ secrets.SONATYPE_USERNAME }}"
          ORG_GRADLE_PROJECT_sonatypePassword: "${{ secrets.SONATYPE_PASSWORD }}"
          ORG_GRADLE_PROJECT_stellardriftUsername: "${{ secrets.STELLARDRIFT_USERNAME }}"
          ORG_GRADLE_PROJECT_stellardriftPassword: "${{ secrets.STELLARDRIFT_PASSWORD }}"
          ORG_GRADLE_PROJECT_papermcUsername: "${{ secrets.PAPERMC_USERNAME }}"
          ORG_GRADLE_PROJECT_papermcPassword: "${{ secrets.PAPERMC_PASSWORD }}"
          ORG_GRADLE_PROJECT_kyoriSigningKey: "${{ secrets.KYORI_GPG_KEY }}"
          ORG_GRADLE_PROJECT_kyoriSigningPassword: "${{ secrets.KYORI_GPG_PASSWORD }}"
          ORG_GRADLE_PROJECT_kyoriUsername: "${{ secrets.KYORI_REPO_USERNAME }}"
          ORG_GRADLE_PROJECT_kyoriPassword: "${{ secrets.KYORI_REPO_PASSWORD }}"
      - name: "publish release"
        if: "${{ inputs.publish_releases && runner.os == 'Linux' && env.STATUS == 'release' && github.event_name == 'release' }}"
        run: "./gradlew ${{ inputs.extra_gradle_params }} ${{ inputs.gradle_release_publish_tasks }} ${{ inputs.extra_gradle_publish_params }}"
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: "${{ secrets.SONATYPE_USERNAME }}"
          ORG_GRADLE_PROJECT_sonatypePassword: "${{ secrets.SONATYPE_PASSWORD }}"
          ORG_GRADLE_PROJECT_kyoriSigningKey: "${{ secrets.KYORI_GPG_KEY }}"
          ORG_GRADLE_PROJECT_kyoriSigningPassword: "${{ secrets.KYORI_GPG_PASSWORD }}"
          ORG_GRADLE_PROJECT_pluginPortalApiKey: "${{ secrets.KYORI_PLUGIN_PORTAL_KEY }}"
          ORG_GRADLE_PROJECT_pluginPortalApiSecret: "${{ secrets.KYORI_PLUGIN_PORTAL_SECRET }}"
      - name: "copy javadoc for publication"
        if: "${{ inputs.publish_release_javadoc && runner.os == 'Linux' && env.STATUS == 'release' && github.event_name == 'release' }}"
        run: |
          mkdir -p build/publish-jd/${{ inputs.javadoc_deploy_prefix }}
          ./gradlew ${{ inputs.extra_gradle_params }} copyJavadoc --output build/publish-jd/${{ inputs.javadoc_deploy_prefix }}
      - name: "authenticate for javadoc publication"
        if: "${{ inputs.publish_release_javadoc && runner.os == 'Linux' && env.STATUS == 'release' && github.event_name == 'release' }}"
        uses: "tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a" # v2.1.0
        id: jd-token
        with:
          app_id: "${{ secrets.DEPLOYMENT_APP_ID }}"
          private_key: "${{ secrets.DEPLOYMENT_APP_SECRET }}"
          installation_retrieval_mode: "repository"
          installation_retrieval_payload: "KyoriPowered/adventure-javadocs"
      - name: "publish javadoc"
        if: "${{ inputs.publish_release_javadoc && runner.os == 'Linux' && env.STATUS == 'release' && github.event_name == 'release' }}"
        uses: JamesIves/github-pages-deploy-action@6c2d9db40f9296374acc17b90404b6e8864128c8 # v4.7.3
        with:
          folder: build/publish-jd
          repository-name: KyoriPowered/adventure-javadocs
          token: ${{ steps.jd-token.outputs.token }}
          branch: main
          git-config-name: kyoripowered-deployment[bot]
          git-config-email: "121842021+kyoripowered-deployment[bot]@users.noreply.github.com"
          clean: false
          force: false
          commit-message: "Publishing javadoc for ${{ github.repository }} ${{ env.PROJECT_VERSION }}"
  upload-dependencies:
    name: "submit dependency graph"
    # try to run on build failure too?
    if: github.event_name == 'push' && always()
    needs: "build"
    runs-on: "ubuntu-latest"
    permissions:
      contents: "write"
    steps:
      - name: "check branch for publish"
        uses: "KyoriPowered/action-regex-match@1ff8ef914f6762fff8d5efd8d56ef88b5be5dd5c" # v4.0.0
        id: "branch-name"
        with:
          text: "${{ github.ref }}"
          regex: "^refs/heads/(?:${{ inputs.publishing_branch_regex }})$" # master or something like 0.8.x or 2.x
      - name: "submit dependency graph"
        uses: "gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2" # v5.0.0
        if: steps.branch-name.outputs.match != ''
        with:
          dependency-graph: "download-and-submit"

