name: "Run tests against latest Gradle RC/nightly"

on:
  workflow_call:
    inputs:
      runtime_version:
        description: 'The default Java runtime version to run builds on'
        required: false
        type: number
        default: 11
      injected_version_path:
        description: 'The path to write an injected versions resource (named: injected-gradle-versions) to'
        required: true
        type: string
      extra_gradle_params:
        description: 'Extra arguments to pass to all Gradle invocations'
        required: false
        type: string
        default: ''
      gradle_version:
        description: 'A gradle version override'
        required: false
        type: string
        default: "-"

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

permissions:
  actions: "write"
  contents: "read"

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: "checkout repository"
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: 0
          submodules: true
      - name: "validate gradle wrapper"
        uses: "gradle/wrapper-validation-action@56b90f209b02bf6d1deae490e9ef18b21a389cd4" # v1
      - name: "setup jdk ${{ inputs.runtime_version }}"
        uses: actions/setup-java@cd89f46ac9d01407894225f350157564c9c7cee2 # v3
        with:
          distribution: "temurin"
          java-version: "${{ inputs.runtime_version }}"
      - name: "determine target version"
        uses: "KyoriPowered/get-gradle-versions@bf11a85fe6820abac2ab7dace3aeea6375dd1fab" # v1
        id: "determine-target"
        with:
          override: "${{ inputs.gradle_version }}"
          output_file: "${{ inputs.injected_version_path }}/injected-gradle-versions"
      - name: "run gradle build / added tests on ${{ steps.determine-target.outputs.latest_rc_or_nightly }}"
        uses: "gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc" # v2
        if: "${{ steps.determine-target.outputs.latest_rc_or_nightly }}"
        with:
          cache-read-only: true
          arguments: "${{ inputs.extra_gradle_params }} build"
      - name: "archive test results"
        if: "${{ always() }}"
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: "${{ runner.os }}-test-results"
          path: |
            build/reports/
            */build/reports/
      - name: "run gradle build / compiling on ${{ steps.determine-target.outputs.latest_rc_or_nightly }}"
        uses: "gradle/gradle-build-action@ef76a971e2fa3f867b617efd72f2fbd72cf6f8bc" # v2
        if: "${{ always() && steps.determine-target.outputs.latest_rc_or_nightly }}"
        with:
          cache-read-only: true
          gradle-version: "${{ steps.determine-target.outputs.latest_rc_or_nightly }}"
          arguments: "${{ inputs.extra_gradle_params }} build --warning-mode=all"
