name: Run CI

on:
  workflow_call:
    inputs:
      runtime_version:
        description: 'The default Java runtime version to run builds on'
        required: false
        type: number
        default: 17
      publishing_branch_regex:
        description: 'The regular expression to determine if a certain branch build should be published'
        required: false
        type: string
        default: '(?:(?:(?:main\/)?(\d+(?:\.\d+)*(?:\.x)?)))|master|main|trunk'
      extra_gradle_params:
        description: 'Extra arguments to pass to all Gradle invocations'
        required: false
        type: string
        default: ''
      extra_gradle_publish_params:
        description: 'Extra arguments to pass to the Gradle invocation that publishes this project'
        required: false
        type: string
        default: ''
      gradle_release_publish_tasks:
        description: 'Extra tasks to pass to the Gradle invocation that publishes releases of this project'
        required: false
        type: string
        default: 'publishToSonatype closeAndReleaseSonatypeStagingRepository'
      gradle_warning_mode:
        description: 'Warning mode to set on Gradle executions'
        required: false
        type: string
        default: 'fail'
      publish_releases:
        description: 'Whether to publish releases of this project. The gradle_release_publish_params input must be provided when publishing to anything but Sonatype Central'
        required: false
        type: boolean
        default: false
      publish_release_javadoc:
        description: 'Whether to publish Javadocs on release'
        required: false
        type: boolean
        default: false
      javadoc_deploy_prefix:
        description: 'Extra subdirectory to publish javadoc under'
        required: false
        type: string
        default: ''
    secrets:
      SONATYPE_USERNAME:
        description: 'Kyori OSSRH Username'
        required: false
      SONATYPE_PASSWORD:
        description: 'Kyori OSSRH Password'
        required: false
      STELLARDRIFT_USERNAME:
        description: 'Kyori Stellardrift Repository Username'
        required: false
      STELLARDRIFT_PASSWORD:
        description: 'Kyori Stellardrift Repository Password'
        required: false
      PAPERMC_USERNAME:
        description: 'Kyori PaperMC Repository Username'
        required: false
      PAPERMC_PASSWORD:
        description: 'Kyori PaperMC Repository Password'
        required: false
      KYORI_REPO_USERNAME:
        description: 'Kyori Repository Username'
        required: false
      KYORI_REPO_PASSWORD:
        description: 'Kyori Repository Password'
        required: false
      KYORI_GPG_KEY:
        description: 'Kyori GPG signing key'
        required: false
      KYORI_GPG_PASSWORD:
        description: 'Kyori GPG signing password'
        required: false
      DEPLOYMENT_APP_ID:
        description: 'App id for JD publisher'
        required: false
      DEPLOYMENT_APP_SECRET:
        description: 'App key for JD publisher'
        required: false
      KYORI_PLUGIN_PORTAL_API_KEY:
        description: 'Kyori Gradle Plugin Portal API key'
        required: false
      KYORI_PLUGIN_PORTAL_API_SECRET:
        description: 'Kyori Gradle Plugin Portal API secret'
        required: false

permissions:
  actions: "write"
  contents: "write"
  id-token: "write"

jobs:
  call-build:
    uses: "KyoriPowered/ci-cookbook/.github/workflows/java-ci.yaml@5f3b529fd5d1fe99cd40b52eec128a01607850fb" # 2026.01.11
    with:
      runtime_version: "${{ inputs.runtime_version }}"
      publishing_branch_regex: "${{ inputs.publishing_branch_regex }}"
      extra_gradle_params: "${{ inputs.extra_gradle_params }}"
      extra_gradle_publish_params: "${{ inputs.extra_gradle_publish_params }}"
      gradle_release_publish_tasks: "${{ inputs.gradle_release_publish_tasks }}"
      gradle_warning_mode: "${{ inputs.gradle_warning_mode }}"
      publish_releases: "${{ inputs.publish_releases }}"
      publish_release_javadoc: "${{ inputs.publish_release_javadoc }}"
      javadoc_deploy_prefix: "${{ inputs.javadoc_deploy_prefix }}"
    secrets:
      DEPLOYMENT_APP_ID: "${{ secrets.DEPLOYMENT_APP_ID }}"
      DEPLOYMENT_APP_SECRET: "${{ secrets.DEPLOYMENT_APP_SECRET }}"
      publishing_env_vars: |
          ORG_GRADLE_PROJECT_sonatypeUsername="${{ secrets.SONATYPE_USERNAME }}"
          ORG_GRADLE_PROJECT_sonatypePassword="${{ secrets.SONATYPE_PASSWORD }}"
          ORG_GRADLE_PROJECT_stellardriftUsername="${{ secrets.STELLARDRIFT_USERNAME }}"
          ORG_GRADLE_PROJECT_stellardriftPassword="${{ secrets.STELLARDRIFT_PASSWORD }}"
          ORG_GRADLE_PROJECT_papermcUsername="${{ secrets.PAPERMC_USERNAME }}"
          ORG_GRADLE_PROJECT_papermcPassword="${{ secrets.PAPERMC_PASSWORD }}"
          ORG_GRADLE_PROJECT_kyoriSigningKey="${{ secrets.KYORI_GPG_KEY }}"
          ORG_GRADLE_PROJECT_kyoriSigningPassword="${{ secrets.KYORI_GPG_PASSWORD }}"
          ORG_GRADLE_PROJECT_kyoriUsername="${{ secrets.KYORI_REPO_USERNAME }}"
          ORG_GRADLE_PROJECT_kyoriPassword="${{ secrets.KYORI_REPO_PASSWORD }}"
          ORG_GRADLE_PROJECT_pluginPortalApiKey="${{ secrets.KYORI_PLUGIN_PORTAL_KEY }}"
          ORG_GRADLE_PROJECT_pluginPortalApiSecret="${{ secrets.KYORI_PLUGIN_PORTAL_SECRET }}"
