name: "Validate Renovate Configuration"

on:
  push:
    paths:
    - "renovate-config.json"
  pull_request:
    paths:
    - "renovate-config.json"

jobs:
  validate:
    # Only run on PRs if the source branch is on someone else's repo
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: suzuki-shunsuke/github-action-renovate-config-validator@ee9f69e1f683ed0d08225086482b34fc9abe9300 # v2.1.0
      with:
        config_file_path: renovate-config.json
