name: "Validate Renovate Configuration"

on:
  push:
    paths:
    - "renovate-config.json"
  pull_request:
    paths:
    - "renovate-config.json"

jobs:
  validate:
    # Only run on PRs if the source branch is on someone else's repo
    if: "${{ github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name }}"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
    - uses: suzuki-shunsuke/github-action-renovate-config-validator@b850926b611b1f3d3fe3729776339c217834bf2c # v2.2.0
      with:
        config_file_path: renovate-config.json
